### ISSUE TITLE
Adding a License

### ISSUE THREAD

**Issue by polarisfm** [Kycklingar/PBooru#1]
Your code seems to have no license. If you want a license that's equivalent to the Public Domain, try the [Unlicense](https://unlicense.org/). If you want everyone that modifies your code be required to publicize changes under the same conditions (copyleft), check out [GPLv3](https://www.gnu.org/licenses/gpl.html). If you want a BSD/MIT-style license, check out [ISC](https://choosealicense.com/licenses/isc/).

It's important to have a license attached to your software so users know exactly what they can and cannot do with the software you've written. Licenses also can and should be used to ensure [User Freedom](https://www.gnu.org/philosophy/free-sw.en.html). Note that a license does not have to be a copyleft license to do this, all licenses recommended are great choices.

Adding a license can easily be done on GitHub through the repository settings.

Thanks!

**Comment by Kycklingar** [comment]
Done
