### ISSUE TITLE
PBooru, but for books

### ISSUE THREAD

**Issue by DonaldTsang** [Kycklingar/PBooru#13]
Idea: PBooru, but have PDFs, EPUBs and MOBIs instead. Like Libgen or SciHub.
And of course all of the books are tagged so that related items can be easily found.

**Comment by Kycklingar** [comment]
I pushed changes to master which will allow you to specify what mime types are allowed to be uploaded. Files that are not an image nor a video will have empty thumbnails and post bodies for now.

**Comment by DonaldTsang** [comment]
@Kycklingar what about using thumbnails? PDF has https://github.com/bakape/thumbnailer and https://github.com/btimby/thumbnailer while EPUB has https://github.com/marianosimone/epub-thumbnailer and https://github.com/Caig/kde-thumbnailer-epub with MOBI having https://github.com/GNOME/gnome-epub-thumbnailer

**Comment by Kycklingar** [comment]
I was thinking showing important tags like creator and title on the thumbnail slot but a thumbnail image might be good to.

**Comment by DonaldTsang** [comment]
Yes!
