### ISSUE TITLE
WebP, FLIF and AVIF support

### ISSUE THREAD

**Issue by DonaldTsang** [Kycklingar/PBooru#14]
Some newer image formats with better compression.

**Comment by Kycklingar** [comment]
I'll see if ImageMagick can handle them. #12

**Comment by DonaldTsang** [comment]
- WebP and HEIF is on its way out for imagemagick
- AVIF https://github.com/ImageMagick/ImageMagick/issues/1432
- Dunno about FLIF

**Comment by dlemstra** [comment]
@DonaldTsang ImageMagick also support FLIF.

**Comment by DonaldTsang** [comment]
@dlemstra give me a high five for all these image format support.

**Comment by DonaldTsang** [comment]
@Kycklingar any test coverage for this?

**Comment by Kycklingar** [comment]
@DonaldTsang Sorry missed your comment.
No there are no tests atm. I've only done manual tests. I noticed there were some problems with FLIF which was rectified in a59eeac. Also what image format is supported very much depends on your Image Magick installation. You can use ```identify -list format``` to check.
