### ISSUE TITLE
Tags.html page gives permision error even when logged

### ISSUE THREAD

**Issue by Gabrielcmf** [Kycklingar/PBooru#66]
I'm sorry if this is not the right place to post bug reports, but the tags.html page on the tpb gives a "Insufficient privileges. Want Tags " message, even though I'm logged in.

Steps:
1 - Access http://vsdfdtkr5mh6y33p.onion/tags/
2-Select a tag
3-Select another tag
4-Click submit query

I can give more login info if you need it

**Comment by Kycklingar** [comment]
This is the best place for reporting issues. This isn't as much a bug as it is a lack of clarity. There are confusingly two privileges for tags: 'Tagging' and 'Tags'. One is for applying tags to a post while the other if for altering tag behaviour. You are lacking the later, required one.
Obviously being served forms you can not use isn't good design. Will fix.

**Comment by Gabrielcmf** [comment]
Ok, thanks for clearing that up,
