### ISSUE TITLE
Gateway timeout 

### ISSUE THREAD

**Issue by Nightshadow64** [Kycklingar/PBooru#82]
Hello,
I have a problem with the website you made for all the pictures. So I have a few questions on what to do and explain what is wrong.

So
First of all I was able to normally access the site About 2 weeks ago. Everything was working fine.
But for almost one week now it's not really working.
I can click on all things like "home" "posts" "wall" and all that and get there no problem. But I cant get any further.
If I click any picture I get the 504 Gateway time out. Same is if I try to search for tags or write a comment on the wall.
My question now is? Is the site/the server down? Or am I missing something?
Ps: I tried accessing it with Google Chrome on my phone(which was working perfectly 2 weeks ago) and on my laptop as well as with the Tor browser but I wasn't able to do anything.
I hope someone can help me.
Thanks in Advance

**Comment by Kycklingar** [comment]
Post the link you are using.

**Comment by Nightshadow64** [comment]
https://owmvhpxyisu6fgd7r2fcswgavs7jly4znldaey33utadwmgbbp4pysad.onion.ly/

It's this one

**Comment by Nightshadow64** [comment]
Also, it is working fine again for around 10 hours by now

**Comment by Kycklingar** [comment]
Notice the `.ly`. That's a tor2web gateway, it's going to be flaky at best.
The best and most reliable way to access the site is through the tor browser (orbot on android) on the following address:
http://owmvhpxyisu6fgd7r2fcswgavs7jly4znldaey33utadwmgbbp4pysad.onion

If you must use a normal browser you can try any of the following tor2web gateways:
https://owmvhpxyisu6fgd7r2fcswgavs7jly4znldaey33utadwmgbbp4pysad.onion.dog
https://owmvhpxyisu6fgd7r2fcswgavs7jly4znldaey33utadwmgbbp4pysad.onion.pet
https://owmvhpxyisu6fgd7r2fcswgavs7jly4znldaey33utadwmgbbp4pysad.onion.ws
Word of caution. Do not send passwords, register, or login over a tor2web gateway, only do regular browsing. They can see everything being sent and received.

**Comment by Nightshadow64** [comment]
Alright then. Thanks for clearing things up. Keep up the great work you put into this site
